# Generated by Django 3.1.3 on 2023-03-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='ingeneer',
        ),
        migrations.RemoveField(
            model_name='livrable',
            name='type',
        ),
        migrations.AddField(
            model_name='commission',
            name='engineer',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='datSignaMoa',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='delays',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='souscriptionDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='holder',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='livrable',
            name='typeLivrable',
            field=models.CharField(choices=[('I', 'Imprevu'), ('A', 'Attendu')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='cautionnement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='comptable',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='csm',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='commission',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='president',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='Consistancy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='typePassation',
            field=models.CharField(choices=[('AONO', 'A Offre Nat Ouvert'), ('AONR', 'A Offre Nat Restreint'), ('AC', 'Proc Accord Cadre'), ('AOIO', 'A Offre Int Ouvert'), ('AOIR', 'A Offre Int Restreint'), ('AONC', 'A Offre Nat Concours'), ('AOIC', 'A Offre Int Concours'), ('AO2', 'A Offre 2 Etapes'), ('GAG', 'Proc Gre A Gre'), ('DC', 'Proc Demande Cotation'), ('CI', 'Proc Consult Individuelle')], default='AONO', max_length=5),
        ),
        migrations.AlterField(
            model_name='financement',
            name='guichet',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='financement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='financement',
            name='imputation',
            field=models.CharField(max_length=21),
        ),
        migrations.AlterField(
            model_name='financement',
            name='source',
            field=models.CharField(choices=[('BIP', 'Budget Investissement Public'), ('FINEX', 'Financement Exterieur')], default='BIP', max_length=15),
        ),
        migrations.AlterField(
            model_name='holder',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='holder',
            name='poBox',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='livrable',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='livrable',
            name='nature',
            field=models.CharField(choices=[('FO', 'Fournitures'), ('TR', 'Travaux'), ('SQ', 'Sces Quantifiable'), ('PI', 'Pres Intellectuelle'), ('CR', 'Concept Realisation'), ('AC', 'Accord Cadre'), ('PT', 'Pluriannuel Tranche'), ('RE', 'Reserve'), ('SP', 'Special')], default='TR', max_length=2),
        ),
        migrations.AlterField(
            model_name='localization',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='localization',
            name='localite',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='montant',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
