# Generated by Django 3.1.3 on 2023-03-28 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_contract_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='caution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.cautionnement'),
        ),
        migrations.AddField(
            model_name='contract',
            name='commission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.commission'),
        ),
        migrations.AddField(
            model_name='contract',
            name='financement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.financement'),
        ),
        migrations.AddField(
            model_name='contract',
            name='holder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.holder'),
        ),
        migrations.AddField(
            model_name='contract',
            name='localization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.localization'),
        ),
        migrations.AddField(
            model_name='contract',
            name='montant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.montant'),
        ),
        migrations.AddField(
            model_name='livrable',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.contract'),
        ),
        migrations.AlterField(
            model_name='financement',
            name='source',
            field=models.CharField(choices=[('BIP', 'Budget Investissement Public'), ('FINEX', 'Financement Exterieur')], default='BIP', max_length=5),
        ),
    ]
