# Generated by Django 4.1.7 on 2023-04-06 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_exercice_contract_actif_alter_cautionnement_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercice',
            name='suivants',
        ),
    ]
