# Generated by Django 4.1.7 on 2023-04-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_remove_exercice_suivants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='datSignaMoa',
            field=models.DateField(null=True),
        ),
    ]
