# Generated by Django 4.1.7 on 2023-04-07 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_alter_contract_datsignamoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='exercice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.exercice'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='typePassation',
            field=models.CharField(choices=[('AONO', 'Appel Offre Nat Ouvert'), ('AONR', 'Appel Offre Nat Restreint'), ('AC', 'Procedure Accord Cadre'), ('AOIO', 'Appel Offre Int Ouvert'), ('AOIR', 'Appel Offre Int Restreint'), ('AONC', 'Appel Offre Nat Concours'), ('AOIC', 'Appel Offre Int Concours'), ('AO2', 'Appel Offre 2 Etapes'), ('GAG', 'Procedure Gre A Gre'), ('DC', 'Procedure Demande Cotation'), ('CI', 'Procedure Consult Individuelle')], default='AONO', max_length=5),
        ),
    ]
