# Generated by Django 4.1.7 on 2023-04-07 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_contract_unitedelai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='caution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.cautionnement'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='commission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.commission'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='exercice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.exercice'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='financement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.financement'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.holder'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='localization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.localization'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='montant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.montant'),
        ),
    ]
