# Generated by Django 4.1.7 on 2023-04-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_alter_contract_datsignamoa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='revisionPrice',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
