# Generated by Django 4.1.7 on 2023-04-07 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0013_alter_contract_revisionprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='Actif',
            new_name='actif',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='Consistancy',
            new_name='consistancy',
        ),
    ]
