# Generated by Django 4.1.7 on 2023-04-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0015_exercice_autretax_exercice_tauxir_exercice_tauxtva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='autreTax',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
