# Generated by Django 4.1.7 on 2023-04-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0016_alter_exercice_autretax'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='codeExo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
