# Generated by Django 4.1.7 on 2023-04-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0017_exercice_codeexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='montant',
            name='mtAir',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='montant',
            name='mtHtax',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='montant',
            name='mtNet',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='montant',
            name='mtTtc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='montant',
            name='mtTva',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
