# Generated by Django 4.1.7 on 2023-04-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0020_alter_financement_imputation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livrable',
            name='libelle',
            field=models.CharField(max_length=200),
        ),
    ]
