# Generated by Django 4.1.7 on 2023-04-17 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0021_alter_livrable_libelle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Livrable',
        ),
    ]
