# Generated by Django 4.1.7 on 2023-05-09 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0022_delete_livrable'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='authorCo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='chapitre',
            field=models.CharField(choices=[('94', 'Intervention En Investissement'), ('22', 'Economie Planification Et Amenagament Du Territoire')], default='22', max_length=2),
        ),
        migrations.AddField(
            model_name='contract',
            name='dateCreated',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='holder',
            name='representant',
            field=models.CharField(default='inconnu', max_length=100),
        ),
    ]
