# Generated by Django 4.1.7 on 2023-05-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0024_commissionmember_memberscommission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='numeroPassation',
            field=models.CharField(default='inconnu', max_length=100),
        ),
        migrations.AddField(
            model_name='contract',
            name='urgencyProcess',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contract',
            name='consistancy',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='object',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contract',
            name='uniteDelai',
            field=models.CharField(choices=[('JR', 'Jours'), ('M', 'Mois')], default='M', max_length=2),
        ),
    ]
