# Generated by Django 4.1.7 on 2023-05-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0025_contract_numeropassation_contract_urgencyprocess_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='numLot',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
