# Generated by Django 4.1.7 on 2023-05-12 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0026_alter_contract_numlot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default="BUDGET D'INVESTISSEMENT PUBLIC", max_length=50)),
                ('code', models.CharField(default='BIP', max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='contract',
            name='chapitre',
            field=models.CharField(choices=[('94', 'Intervention En Investissement'), ('22', 'Economie Planification Et Amenagement Du Territoire')], default='22', max_length=2),
        ),
        migrations.CreateModel(
            name='Guichet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guichet', models.CharField(default='Paierie Générale du Trésor', max_length=30)),
                ('imputation', models.CharField(max_length=27, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.ressource')),
            ],
        ),
        migrations.AlterField(
            model_name='contract',
            name='financement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.guichet'),
        ),
        migrations.DeleteModel(
            name='Financement',
        ),
    ]
