# Generated by Django 4.1.7 on 2023-04-17 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0022_delete_livrable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=200)),
                ('txDecompte', models.IntegerField()),
                ('datSignaCsm', models.DateField()),
                ('datSignaIng', models.DateField()),
                ('datSignaMoa', models.DateField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract')),
                ('montant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.montant')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('dateEvent', models.DateField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etatExec', models.IntegerField(choices=[('1', 'En Cours'), ('2', 'Non Debute'), ('3', 'En Arret')], default=2)),
                ('txExecPhy', models.IntegerField(null=True)),
                ('nbreAvenant', models.IntegerField(null=True)),
                ('nbreDecompte', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numBonEnga', models.CharField(max_length=20)),
                ('datPaiement', models.DateField()),
                ('modePaiement', models.CharField(choices=[('V', 'Virement'), ('E', 'En Especes'), ('I', 'Inconnu')], default='V', max_length=2)),
                ('decompte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='execution.decompte')),
            ],
        ),
        migrations.CreateModel(
            name='Livrable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(choices=[('FO', 'Fournitures'), ('TR', 'Travaux'), ('SQ', 'Sces Quantifiable'), ('PI', 'Pres Intellectuelle'), ('CR', 'Concept Realisation'), ('AC', 'Accord Cadre'), ('PT', 'Pluriannuel Tranche'), ('RE', 'Reserve'), ('SP', 'Special')], default='TR', max_length=2)),
                ('libelle', models.CharField(max_length=200)),
                ('typeLivrable', models.CharField(choices=[('I', 'Imprevu'), ('A', 'Attendu')], default='A', max_length=1)),
                ('isRealized', models.BooleanField(default=False)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='execution.event')),
            ],
        ),
        migrations.CreateModel(
            name='Avenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetAvenant', models.CharField(max_length=250)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract')),
                ('montant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.montant')),
            ],
        ),
    ]
