# Generated by Django 4.1.7 on 2023-04-18 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avenant',
            name='dateAvenant',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avenant',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='execution.event'),
        ),
        migrations.AddField(
            model_name='executioncontrat',
            name='nbreOs',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='livrable',
            name='datValidation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livrable',
            name='isReceive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='decompte',
            name='datSignaCsm',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='decompte',
            name='datSignaIng',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='decompte',
            name='datSignaMoa',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='dateEvent',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='livrable',
            name='nature',
            field=models.CharField(choices=[('FO', 'Fournitures'), ('TR', 'Travaux'), ('SQ', 'Sces Quantifiables'), ('PI', 'Pres Intellectuelle'), ('CR', 'Concept Realisation'), ('AC', 'Accord Cadre'), ('PT', 'Pluriannuel Tranche'), ('RE', 'Reserve'), ('SP', 'Special')], default='TR', max_length=2),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='datPaiement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Ordre_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerOs', models.CharField(blank=True, max_length=50, null=True)),
                ('motifOs', models.CharField(max_length=250)),
                ('datOs', models.DateField(blank=True, null=True)),
                ('typeOs', models.CharField(choices=[('D', 'Demarrage'), ('S', 'Suspension'), ('L', 'Reprise'), ('T', 'Technique'), ('SR', 'Suspension Reprise')], default='D', max_length=2)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='execution.event')),
            ],
        ),
    ]
