# Generated by Django 4.1.7 on 2023-04-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0002_remove_avenant_contract_avenant_datavenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dateEvent',
            field=models.DateField(blank=True, null=True),
        ),
    ]
