# Generated by Django 4.1.7 on 2023-04-24 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0003_remove_avenant_contract_alter_event_dateevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['dateEvent']},
        ),
    ]
