# Generated by Django 4.1.7 on 2023-04-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0004_alter_event_options_remove_avenant_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordre_service',
            name='typeOs',
            field=models.CharField(choices=[('D', 'Demarrage'), ('S', 'Suspension'), ('R', 'Reprise'), ('T', 'Technique'), ('SR', 'Suspension Reprise')], default='D', max_length=2),
        ),
    ]
