# Generated by Django 4.1.7 on 2023-05-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0005_remove_avenant_contract_alter_ordre_service_typeos'),
    ]

    operations = [
        migrations.AddField(
            model_name='decompte',
            name='datDecompte',
            field=models.DateField(blank=True, null=True),
        ),
    ]
