# Generated by Django 4.1.7 on 2023-05-09 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('execution', '0006_remove_avenant_contract_decompte_datdecompte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paiement',
            old_name='numBonEnga',
            new_name='numero',
        ),
        migrations.RemoveField(
            model_name='avenant',
            name='contract',
        ),
        migrations.AddField(
            model_name='avenant',
            name='authorAv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='decompte',
            name='authorDe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='authorEv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livrable',
            name='authorLi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordre_service',
            name='authorOs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paiement',
            name='authorPa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paiement',
            name='modEngagement',
            field=models.CharField(choices=[('BON', 'Bon Engagement'), ('DEC', 'Decision Engagement')], default='BON', max_length=3),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='modePaiement',
            field=models.CharField(choices=[('V', 'Virement'), ('E', 'En Especes'), ('I', 'Inconnu')], default='I', max_length=2),
        ),
    ]
